[package]
name = "ike-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
keyboard-types = "0.8"
cursor-icon = "1.2"

seahash = "4"
tracing = "0.1"
bitflags = "2"
